# Generated by Django 3.2.7 on 2021-12-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eapi', '0002_auto_20211214_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('books', models.ManyToManyField(to='eapi.BookModel')),
                ('product', models.ManyToManyField(to='eapi.ProductModel')),
            ],
            options={
                'ordering': ['cart_id', '-date_created'],
            },
        ),
    ]
